networks:
  1panel-network:
    external: true
services:
  kirara-agent:
    container_name: kirara-agent
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: lss233/kirara-agent-framework:v3.2.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    restart: always
    volumes:
    - ${KIRARA_AGENT_ROOT_PATH}/data:/app/data
