networks:
  1panel-network:
    external: true
services:
  lucky:
    container_name: ${CONTAINER_NAME}
    entrypoint:
    - /app/conf/start.sh
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: gdy666/lucky:2.23.1
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE:-host}
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
    volumes:
    - ./run/start.sh:/app/conf/start.sh:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ${LUCKY_ROOT_PATH}/data:/app/conf
