networks:
  1panel-network:
    external: true
services:
  twikoo:
    container_name: ${CONTAINER_NAME}
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - TWIKOO_PORT=8080
    image: imaegoo/twikoo:1.6.44
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    restart: always
    volumes:
    - ${TWIKOO_ROOT_PATH}/data:/app/data
