networks:
  1panel-network:
    external: true
services:
  libretranslate:
    container_name: libretranslate
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - LT_API_KEYS=true
    healthcheck:
      interval: 10s
      retries: 4
      start_period: 5s
      test:
      - CMD-SHELL
      - ./venv/bin/python scripts/healthcheck.py
      timeout: 4s
    image: libretranslate/libretranslate:v1.9.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5000
    restart: always
    volumes:
    - ${LIBRETRANSLATE_ROOT_PATH}/db:/app/db
    - ${LIBRETRANSLATE_ROOT_PATH}/models:/home/libretranslate/.local:rw
