networks:
  1panel-network:
    external: true
services:
  woodpecker-agent:
    command: agent
    depends_on:
    - woodpecker-server
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - WOODPECKER_SERVER=woodpecker-server:9000
    - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    image: woodpeckerci/woodpecker-agent:v3.12.0
    networks:
    - 1panel-network
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${WOODPECKER_ROOT_PATH}/agent:/etc/woodpecker
  woodpecker-server:
    container_name: woodpecker
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - WOODPECKER_OPEN=true
    - WOODPECKER_SERVER_ADDR=:8000
    - WOODPECKER_GRPC_ADDR=:9000
    - WOODPECKER_HOST=${WOODPECKER_HOST}
    - WOODPECKER_GITHUB=true
    - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
    - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
    - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    image: woodpeckerci/woodpecker-server:v3.12.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8000
    restart: always
    volumes:
    - ${WOODPECKER_ROOT_PATH}/server:/var/lib/woodpecker/
