networks:
  1panel-network:
    external: true
services:
  lucky:
    container_name: lucky
    entrypoint:
    - /goodluck/start.sh
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: gdy666/lucky:2.20.2
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE:-host}
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
    volumes:
    - ./run/start.sh:/goodluck/start.sh:ro
    - ${LUCKY_ROOT_PATH}/data:/goodluck
