networks:
  1panel-network:
    external: true
services:
  neko-master:
    container_name: neko-master
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - NODE_ENV=production
    - DB_PATH=/app/data/stats.db
    image: foru17/neko-master:1.3.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    - ${PANEL_APP_PORT_WS}:3002
    restart: always
    volumes:
    - ${NEKO_MASTER_ROOT_PATH}/data:/app/data
