networks:
  1panel-network:
    external: true
services:
  omnibox:
    container_name: omnibox
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: lampon/omnibox:v1.4.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:7023
    restart: always
    volumes:
    - ${OMNIBOX_ROOT_PATH}/data:/app/data
