networks:
  1panel-network:
    external: true
services:
  napcat:
    container_name: napcat
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - NAPCAT_UID=${NAPCAT_UID:-0}
    - NAPCAT_GID=${NAPCAT_GID:-0}
    image: mlikiowa/napcat-docker:v4.14.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6099
    - ${PANEL_APP_PORT_ONEBOT_HTTP}:3000
    - ${PANEL_APP_PORT_ONEBOT_WS}:3001
    restart: always
    volumes:
    - ${NAPCAT_ROOT_PATH}/data:/app/.config/QQ
    - ${NAPCAT_ROOT_PATH}/napcat:/app/napcat/config
