networks:
  1panel-network:
    external: true
services:
  waline:
    container_name: waline
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - SQLITE_PATH=/app/data
    - SQLITE_DB=waline
    - SQLITE_PREFIX=wl_
    image: lizheming/waline:1.36.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8360
    restart: always
    volumes:
    - ${WALINE_ROOT_PATH}/data:/app/data
