networks:
  1panel-network:
    external: true
services:
  uptime-kuma:
    container_name: uptime-kuma
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - UPTIME_KUMA_HOST=0.0.0.0
    - UPTIME_KUMA_PORT=3001
    - UPTIME_KUMA_DB_TYPE=${UPTIME_KUMA_DB_TYPE:-sqlite}
    - UPTIME_KUMA_DB_HOSTNAME=${UPTIME_KUMA_DB_HOSTNAME:-127.0.0.1}
    - UPTIME_KUMA_DB_PORT=${UPTIME_KUMA_DB_PORT:-3306}
    - UPTIME_KUMA_DB_NAME=${UPTIME_KUMA_DB_NAME:-uptime_kuma}
    - UPTIME_KUMA_DB_USERNAME=${UPTIME_KUMA_DB_USERNAME:-root}
    - UPTIME_KUMA_DB_PASSWORD=${UPTIME_KUMA_DB_PASSWORD:-}
    image: louislam/uptime-kuma:2.1.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3001
    restart: always
    volumes:
    - ${UPTIME_KUMA_ROOT_PATH}/data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
