networks:
  1panel-network:
    external: true
services:
  apprise:
    container_name: apprise
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - APPRISE_STATEFUL_MODE=simple
    - APPRISE_WORKER_COUNT=1
    - APPRISE_ADMIN=y
    image: caronc/apprise:v1.3.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8000
    restart: always
    volumes:
    - ${APPRISE_ROOT_PATH}/config:/config
    - ${APPRISE_ROOT_PATH}/plugin:/plugin
    - ${APPRISE_ROOT_PATH}/attach:/attach
