networks:
  1panel-network:
    external: true
services:
  outline:
    container_name: outline
    env_file:
    - ./envs/global.env
    - ./envs/outline.env
    - .env
    environment:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTP_PROXY}
    - NO_PROXY=${NO_PROXY}
    - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE_NAME}
    image: outlinewiki/outline:1.5.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
    volumes:
    - ${OUTLINE_ROOT_PATH}/data:/var/lib/outline/data
