networks:
  1panel-network:
    external: true
services:
  opengist:
    container_name: opengist
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - OG_SQLITE_JOURNAL_MODE=WAL
    - OG_HTTP_HOST=0.0.0.0
    - OG_HTTP_PORT=6157
    - OG_SSH_HOST=0.0.0.0
    - OG_SSH_PORT=2222
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD-SHELL
      - curl -f http://localhost:6157/healthcheck
      timeout: 10s
    image: thomiceli/opengist:1.11.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6157
    restart: always
    volumes:
    - ${OPENGIST_ROOT_PATH}/.opengist:/opengist
