networks:
  1panel-network:
    external: true
services:
  llonebot:
    container_name: llonebot
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: initialencounter/llonebot:latest
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3080
    - ${PANEL_APP_PORT_ONEBOT_HTTP}:3000
    - ${PANEL_APP_PORT_ONEBOT_WS}:3001
    - ${PANEL_APP_PORT_SATORI}:5600
    restart: always
    volumes:
    - ${LLONEBOT_ROOT_PATH}/data:/root/.config/QQ
    - ${LLONEBOT_ROOT_PATH}/llonebot:/root/llonebot
