networks:
  1panel-network:
    external: true
services:
  archisteamfarm:
    container_name: archisteamfarm
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: justarchi/archisteamfarm:6.3.2.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    restart: always
    volumes:
    - ${ARCHISTEAMFARM_ROOT_PATH}/config:/app/config
    - ${ARCHISTEAMFARM_ROOT_PATH}/plugins:/app/plugins
    - ${ARCHISTEAMFARM_ROOT_PATH}/logs:/app/logs
