networks:
  1panel-network:
    external: true
services:
  mx-mongo:
    container_name: mongo-${CONTAINER_NAME}
    image: mongo
    networks:
    - 1panel-network
    restart: always
    volumes:
    - ${MX_SERVER_ROOT_PATH}/db:/data/db
  mx-redis:
    container_name: redis-${CONTAINER_NAME}
    image: redis:alpine
    networks:
    - 1panel-network
    restart: always
    volumes:
    - ${MX_SERVER_ROOT_PATH}/redis:/data
  mx-server:
    container_name: ${CONTAINER_NAME}
    depends_on:
    - mx-mongo
    - mx-redis
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - PORT=2333
    - DEMO=false
    - NODE_ENV=production
    - ENCRYPT_ENABLE=false
    - DB_HOST=mx-mongo
    - REDIS_HOST=mx-redis
    image: innei/mx-server:8.4.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:2333
    restart: always
    volumes:
    - ${MX_SERVER_ROOT_PATH}/data:/root/.mx-space
